### ISSUE TITLE
h関数の導入

### ISSUE THREAD

**Issue by hikaru1231** [hikaru1231/lamp_practice#5]
viewのadmin.phpに追記します

**Comment by primestyleus** [comment]
@hikaru1231 さん
view/admin_view.phpはたしかに必要ですね！
他にもviewでprint を使っているところは、ほとんどが必要な箇所となります。
(number_formatを使っている場所は大丈夫です)
ためしに、「<a href="#">テスト商品</a>」「<a href="#">テストユーザ</a>」のように登録してみてみるとわかると思いますが、表示上リンクになるところはすべて対応が必要です。
確認しながらでいいので、いったん実装を進めてみてください。
できたらコミット、PUSH＆プルリクをお願いします。

**Comment by hikaru1231** [comment]
かしこまりました！また夜に進めてみます！
